version: "3"

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce-admin-challenge
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

volumes:
  database:
